version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: restaurant-patong-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: restaurant-patong
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - restaurant-network

  # Optionnel: Interface MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: restaurant-patong-admin-db
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - restaurant-network

volumes:
  mongodb_data:

networks:
  restaurant-network:
    driver: bridge